### PR TITLE
Build, version and publish with CI

### LINKED ISSUE #19: GH actions to build image

### PR DESCRIPTION
**Pull request by vmttn**
## Description
Add CI workflows to build and publish repo's images:

* [x] identity-provider
* [ ] ~~register-hydra-client~~ maybe later

Closes #19 , #33

### CODE REVIEW

**Comment by vmttn** [comment]
Requires to add docker hub credentials to repo settings (@Jasopaum @simonvadee ? :))

**Comment by simonvadee** [comment]
@vmttn we already have secrets at the organization level for docker hub credentials. they're called
`ARKHN_DOCKER_LOGIN` and `ARKHN_DOCKER_PASSWORD`

**Review by simonvadee — APPROVED** [review]
lgtm

**Comment by vmttn** [comment]
Idk why it has not been updated on this PR, but workflow is now ok :

https://github.com/arkhn/identity-provider/actions/runs/323909886

**Pull request merged**
